// PRECIO JUSTO — rawDataScraped
// Generado: 2026-03-07T02:47:51.380Z
// Registros: 92
// Fuente: scrapers automáticos
const rawDataScraped = [
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Pack Arroz Extra Añejo VALLENORTE Gran Reserva...",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 26.8,
    "precioRegular": 36.4,
    "descuento": -26,
    "presentacion": 1,
    "vt": 1,
    "um": "u",
    "pxum": 26.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra Añejo FARAON Naranja Bolsa 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 22.9,
    "precioRegular": 26.9,
    "descuento": -15,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.58
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra COSTEÑO Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 25.9,
    "descuento": -8,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra BELL'S Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 17.9,
    "precioRegular": 19.9,
    "descuento": -10,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.58
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra COSTEÑO Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra Añejo VALLENORTE Gran Reserva Bols...",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 20.9,
    "precioRegular": 26.9,
    "descuento": -22,
    "presentacion": 1,
    "vt": 1,
    "um": "u",
    "pxum": 20.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Añejo Extra COSTEÑO Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 25.9,
    "descuento": -23,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra GRAN CHALAN Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.4,
    "precioRegular": 23.4,
    "descuento": -4,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.48
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra PAISANA Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 21.9,
    "precioRegular": 22.9,
    "descuento": -4,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.38
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra VALLENORTE Gran Reserva Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 4.2,
    "precioRegular": 4.8,
    "descuento": -12,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Integral VALLENORTE Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 5.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 7.47
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz FARAON Añejo Amarillo G3 Bolsa 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 20.5,
    "precioRegular": 21.9,
    "descuento": -6,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.1
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior PAISANA Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 21.9,
    "descuento": -9,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra BELL'S Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 3.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 4.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Integral BELL'S Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 3.79,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.05
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Añejo Amarillo FARAÓN G3 Bolsa 1Kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 4.99,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 4.99
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra PAISANA Bolsa 1Kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 5.8,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 5.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Integral BELL'S Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 23.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.72
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior BELL'S Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 3.1,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 4.13
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior BELL'S Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 17.9,
    "precioRegular": 18.7,
    "descuento": -4,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.58
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Integral COSTEÑO Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 6.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 8.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Añejo Extra COSTEÑO Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 4.7,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6.27
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior Añejo VALLENORTE Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 20.9,
    "precioRegular": 23.9,
    "descuento": -13,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.18
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior PAISANA Bolsa 1Kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 5.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 5.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior VALLENORTE Bolsa 750g",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.33
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Blanco FARAON Extra Añejo Negro Bolsa 5K...",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 22.9,
    "precioRegular": 24.9,
    "descuento": -8,
    "presentacion": 1,
    "vt": 1,
    "um": "u",
    "pxum": 22.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz con Pollo BELL'S Bandeja 200g",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 7.7,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 200,
    "vt": 200,
    "um": "g",
    "pxum": 38.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Superior VALLENORTE Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 18.9,
    "precioRegular": 21.9,
    "descuento": -14,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra Añejo BELL'S Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 22.7,
    "descuento": -12,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Añejo PAISANA Bolsa 5Kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Arroz Extra BELL'S Saco 10Kg",
    "categoria": "Arroz",
    "marca": "Bell's",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 38,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 10,
    "vt": 10,
    "um": "kg",
    "pxum": 3.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Lunch Arroz Chaufa de Pollo LA FLORENCIA 500g",
    "categoria": "Arroz",
    "marca": "Lunch",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 10.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 21
  },
  {
    "fecha": "6/3/2026",
    "super": "Plaza Vea",
    "item": "Lunch Arroz Blanco LA FLORENCIA 500g",
    "categoria": "Arroz",
    "marca": "Lunch",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 6.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 13.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Costeño 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 23.2,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.64
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 5kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Gran Reserva Extra Valle Norte Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Wong Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 18.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Gran Reserva Extra Valle Norte Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Añejo Extra 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 750g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 6.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 8.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Wong 750g",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 3.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 4.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Paisana Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 19.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Añejo Cuisine&Co Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 21.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Cuisine & Co 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 24.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Paisana Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Molino Rojo Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 5.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 5.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Wong Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 4.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 10kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 48.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 10,
    "vt": 10,
    "um": "kg",
    "pxum": 4.89
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Vallenorte 750g",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 5.7,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Wong Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 18.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.7
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Tesoro Del Campo Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 30.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 6.06
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Basmati Riso Scotti Caja 500 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.8,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 45.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Parbolizado Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Añejo Faraón Rojo 5kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Extra 3kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 16.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 3,
    "vt": 3,
    "um": "kg",
    "pxum": 5.63
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Arborio Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 12.4,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 16.53
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Añejo Extra 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 6.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 6.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Añejo Extra Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 4.2,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Glaseado Tesoro Del Campo Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 8.25,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 8.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Tesoro Del Campo Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 5.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 7.33
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Añejo Faraón Rojo 750g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.33
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Costeño 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 22.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.58
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz para Cocina Oriental Mizu 1kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Extra Faraón 500g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 2.99,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 5.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Risotto Arborio Inverni 1kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 36.2,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 36.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Parbolizado Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Mix Kiwicha y Linaza Huella Verde 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 39.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz para Sushi Miyabi-Mai 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 43.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 8.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Valle Norte Primera Cosecha Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 6.53
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 3.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 4.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Valle Norte Primera cosecha Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraon Verde 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 28.7,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 5.74
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Cuisine & Co 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 3.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Extra Añejo 3kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 16.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 3,
    "vt": 3,
    "um": "kg",
    "pxum": 5.63
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Arborio Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 15.6,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 1,
    "vt": 1,
    "um": "kg",
    "pxum": 15.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Japónico para Sushi Bárcidda 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 5.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 11.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Chaufa con Pollo Cuisine & Co 400g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 12.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 400,
    "vt": 400,
    "um": "g",
    "pxum": 32.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 3.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 750,
    "vt": 750,
    "um": "g",
    "pxum": 5.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz con Pollo Cuisine & Co 400g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 14.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 400,
    "vt": 400,
    "um": "g",
    "pxum": 36.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Belén Cuisine & Co 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 20.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 41.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Tostado Choco Krispis Kellogg's 420g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 18.5,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 420,
    "vt": 420,
    "um": "g",
    "pxum": 44.05
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Añejo Superior Valle Norte 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 26,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 5.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Mix Cañihua y Chía Huella Verde 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 39.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Gran Chalán 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.2,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 5,
    "vt": 5,
    "um": "kg",
    "pxum": 4.44
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Chaufa Cuisine & Co 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 11.99,
    "precioRegular": 0,
    "descuento": null,
    "presentacion": 500,
    "vt": 500,
    "um": "g",
    "pxum": 23.98
  }
];
