// PRECIO JUSTO — rawDataScraped
// Generado: 2026-03-06T22:31:33.761Z
// Registros: 153
// Fuente: scrapers automáticos
const rawDataScraped = [
  {
    "fecha": "6/3/2026",
    "super": "Metro",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Arroz",
    "marca": "Rubor",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Refrigeradora Mabe 520L Side By Side No Frost ...",
    "categoria": "Arroz",
    "marca": "Refrigeradora",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 1.75,
    "precioRegular": 2.59,
    "descuento": -32,
    "vt": 520,
    "um": "lt",
    "pxum": 1.75
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Celular Motorola Moto G06 4 + 256Gb Café",
    "categoria": "Arroz",
    "marca": "Celular",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 399,
    "precioRegular": 599,
    "descuento": -33,
    "vt": 256,
    "um": "g",
    "pxum": 1558.59
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Celular Motorola Moto G06 4 + 256Gb Azul",
    "categoria": "Arroz",
    "marca": "Celular",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 399,
    "precioRegular": 599,
    "descuento": -33,
    "vt": 256,
    "um": "g",
    "pxum": 1558.59
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Batwheels Nido Prank",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 69.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 69.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Case Xtrem Trinity 6Xt Spider Black",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 34.96,
    "precioRegular": 49.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 34.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Leggin Pack X2 Niña Circus Yt",
    "categoria": "Arroz",
    "marca": "Leggin",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 17.97,
    "precioRegular": 29.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 17.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Pokemon Pikachu Media",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 55.96,
    "precioRegular": 79.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 55.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Hot Wheels Azul",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.97,
    "precioRegular": 49.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 29.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Bolso + Lonchera + Cartuchera Xt...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 139.3,
    "precioRegular": 199,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 139.3
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Peppa Pig",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 44.97,
    "precioRegular": 74.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 44.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Celular Samsung Galaxy A17 256GB 8GB Negro",
    "categoria": "Arroz",
    "marca": "Celular",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 749,
    "precioRegular": 799,
    "descuento": -6,
    "vt": 256,
    "um": "g",
    "pxum": 2925.78
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Celular Samsung Galaxy A17 256GB 8GB Celeste",
    "categoria": "Arroz",
    "marca": "Celular",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 749,
    "precioRegular": 799,
    "descuento": -6,
    "vt": 256,
    "um": "g",
    "pxum": 2925.78
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Pesas Para Muñeca Y Tobillo 1Kg Fit.365 Rosa",
    "categoria": "Arroz",
    "marca": "Pesas",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 69.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 69.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Tipo Libro Zubito Sweetwave",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 20.97,
    "precioRegular": 29.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 20.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Artesco Tweens Futbol",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 27.96,
    "precioRegular": 39.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 27.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Snoopy Rojo",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 48.96,
    "precioRegular": 69.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 48.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Circus Whale",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.95,
    "precioRegular": 59.95,
    "descuento": -50,
    "vt": 1,
    "um": "u",
    "pxum": 29.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Pokemon Pikachu Media",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 34.96,
    "precioRegular": 49.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 34.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera One Piece Wanted",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 79.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 79.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Bt21",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 32.97,
    "precioRegular": 54.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 32.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Bluey Rosa",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.97,
    "precioRegular": 49.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 29.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Tobogán Con Columpio Torre Azul",
    "categoria": "Arroz",
    "marca": "Tobogán",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 219,
    "precioRegular": 429,
    "descuento": -49,
    "vt": 1,
    "um": "u",
    "pxum": 219
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Gabby'S Dollhouse",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.97,
    "precioRegular": 49.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 29.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Circus Bunny",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.95,
    "precioRegular": 59.95,
    "descuento": -50,
    "vt": 1,
    "um": "u",
    "pxum": 29.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Lonchera + Cartuchera Magic Ofic...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 139.93,
    "precioRegular": 199.9,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 139.93
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Artesco Tweens Futbol",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 76.93,
    "precioRegular": 109.9,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 76.93
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Bolso + Lonchera + Cartuchera Xt...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 139.3,
    "precioRegular": 199,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 139.3
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Artesco Tweens Futbol",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 62.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 62.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Lonchera + Cartuchera Kombat Ofi...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 87.43,
    "precioRegular": 124.9,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 87.43
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila De Ruedas + Lonchera + Cartuchera ...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 89.95,
    "precioRegular": 129,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 89.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Portalaptop Xtrem Gamma 6Xt Dark Olive",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 159.2,
    "precioRegular": 199,
    "descuento": -20,
    "vt": 1,
    "um": "u",
    "pxum": 159.2
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Xtrem Hopper 2.0 6Xt Grey Comic",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 95.4,
    "precioRegular": 159,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 95.4
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Tabla De Pilates Multifuncional Fit.365 Gris",
    "categoria": "Arroz",
    "marca": "Tabla",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 169,
    "precioRegular": 0,
    "descuento": null,
    "vt": 365,
    "um": "g",
    "pxum": 463.01
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Escolar Avengers",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 97.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 97.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Peppa Pig",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.97,
    "precioRegular": 49.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 29.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Juego De Vajilla Floral",
    "categoria": "Arroz",
    "marca": "Juego",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 109,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 109
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Rack Botellas Vino Bamboo 37.5 X 16 X 12 Cm",
    "categoria": "Arroz",
    "marca": "Rack",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 89.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 89.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Artesco Básica Negro",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 17.46,
    "precioRegular": 24.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 17.46
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Among Us",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 47.97,
    "precioRegular": 79.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 47.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Among Us",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 29.97,
    "precioRegular": 49.95,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 29.97
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Cartuchera Case Xtrem University+ 6Xt Mermaid ...",
    "categoria": "Arroz",
    "marca": "Cartuchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 41.96,
    "precioRegular": 59.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 41.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Portalaptop Xtrem Cleveland 6Xt Lila",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 118.3,
    "precioRegular": 169,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 118.3
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Especiero Bamboo",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 79.95,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 79.95
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Bolsa Aseo + Lonchera + Cartuche...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 101.94,
    "precioRegular": 169.9,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 101.94
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Bluey Rosa",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 83.94,
    "precioRegular": 139.9,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 83.94
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Perro Caminador De Peluche My Little Pet Grand...",
    "categoria": "Arroz",
    "marca": "Perro",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 41.96,
    "precioRegular": 59.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 41.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Lonchera Furby",
    "categoria": "Arroz",
    "marca": "Lonchera",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 55.96,
    "precioRegular": 79.95,
    "descuento": -30,
    "vt": 1,
    "um": "u",
    "pxum": 55.96
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Mochila Portalaptop Xtrem Monroe 6Xt Black",
    "categoria": "Arroz",
    "marca": "Mochila",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 95.4,
    "precioRegular": 159,
    "descuento": -40,
    "vt": 1,
    "um": "u",
    "pxum": 95.4
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Set Mochila + Maletín + Lonchera + Cartuchera ...",
    "categoria": "Arroz",
    "marca": "Set",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 179.9,
    "precioRegular": 199.9,
    "descuento": -10,
    "vt": 1,
    "um": "u",
    "pxum": 179.9
  },
  {
    "fecha": "6/3/2026",
    "super": "PlazaVea",
    "item": "Celular Motorola Moto G06 4 + 128Gb Azul",
    "categoria": "Arroz",
    "marca": "Celular",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 379,
    "precioRegular": 499,
    "descuento": -24,
    "vt": 128,
    "um": "g",
    "pxum": 2960.94
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Aceite",
    "marca": "Rubor",
    "tipo": "Vegetal",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Aceite",
    "marca": "Labial",
    "tipo": "Vegetal",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Aceite",
    "marca": "Quita",
    "tipo": "Vegetal",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Costeño 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 23.2,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.64
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 5kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Gran Reserva Extra Valle Norte Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Wong Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 18.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 3.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Gran Reserva Extra Valle Norte Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Gran Reserva",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Añejo Extra 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 750g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 6.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 8.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Wong 750g",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 3.6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 4.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Paisana Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 19.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 3.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Añejo Cuisine&Co Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 21.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Cuisine & Co 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 24.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Paisana Bolsa 5 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Molino Rojo Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 5.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 5.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Wong Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 4.5
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraón Naranja 10kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 48.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 10,
    "um": "kg",
    "pxum": 4.89
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Vallenorte 750g",
    "categoria": "Arroz",
    "marca": "Vallenorte",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 5.7,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Wong Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Wong",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 18.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 3.7
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Tesoro Del Campo Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 30.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 6.06
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Basmati Riso Scotti Caja 500 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.8,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 45.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Parbolizado Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Añejo Faraón Rojo 5kg",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 24.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Extra 3kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 16.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 3,
    "um": "kg",
    "pxum": 5.63
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 4.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Arborio Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 12.4,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 16.53
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Añejo Extra 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 6.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 6.3
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Sazonador Deli Arroz Pack 6 Unid",
    "categoria": "Arroz",
    "marca": "Sazonador",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 1.4,
    "precioRegular": 0,
    "descuento": null,
    "vt": 6,
    "um": "u",
    "pxum": 0.23
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Añejo Extra Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Añejo Extra",
    "clase": null,
    "precioOnline": 4.2,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Glaseado Tesoro Del Campo Bolsa 1 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 8.25,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 8.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Tesoro Del Campo Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 5.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 7.33
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Añejo Faraón Rojo 750g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.33
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Costeño 5kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 22.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.58
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz para Cocina Oriental Mizu 1kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Integral Extra Faraón 500g",
    "categoria": "Arroz",
    "marca": "Faraón",
    "tipo": "Integral",
    "clase": null,
    "precioOnline": 2.99,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 5.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Risotto Arborio Inverni 1kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 36.2,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 36.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Parbolizado Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 7.6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 7.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Mix Kiwicha y Linaza Huella Verde 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 39.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz para Sushi Miyabi-Mai 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 43.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 8.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Valle Norte Primera Cosecha Bolsa 750 g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.73
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Costeño 750g",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 4.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 6.53
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 3.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 4.67
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Superior Valle Norte Primera cosecha Bolsa 5 Kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 23.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.78
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Blanco Extra Añejo Faraon Verde 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 28.7,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 5.74
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Cuisine & Co 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 3.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Costeño Extra Añejo 3kg",
    "categoria": "Arroz",
    "marca": "Costeño",
    "tipo": "Extra Añejo",
    "clase": null,
    "precioOnline": 16.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 3,
    "um": "kg",
    "pxum": 5.63
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Arborio Paisana Bolsa 1 kg",
    "categoria": "Arroz",
    "marca": "Paisana",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 15.6,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "kg",
    "pxum": 15.6
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Japónico para Sushi Bárcidda 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 5.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 11.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Chaufa con Pollo Cuisine & Co 400g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 12.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 400,
    "um": "g",
    "pxum": 32.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Cuisine & Co 750g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 3.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 750,
    "um": "g",
    "pxum": 5.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz con Pollo Cuisine & Co 400g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 14.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 400,
    "um": "g",
    "pxum": 36.25
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Belén Cuisine & Co 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 20.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 41.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Tostado Choco Krispis Kellogg's 420g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 18.5,
    "precioRegular": 0,
    "descuento": null,
    "vt": 420,
    "um": "g",
    "pxum": 44.05
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Añejo Superior Valle Norte 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Superior",
    "clase": null,
    "precioOnline": 26,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 5.2
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Mix Cañihua y Chía Huella Verde 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 19.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 39.8
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Extra Gran Chalán 5kg",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 22.2,
    "precioRegular": 0,
    "descuento": null,
    "vt": 5,
    "um": "kg",
    "pxum": 4.44
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Arroz Chaufa Cuisine & Co 500g",
    "categoria": "Arroz",
    "marca": "Arroz",
    "tipo": "Extra",
    "clase": null,
    "precioOnline": 11.99,
    "precioRegular": 0,
    "descuento": null,
    "vt": 500,
    "um": "g",
    "pxum": 23.98
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Azucar",
    "marca": "Rubor",
    "tipo": "Azucar",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Azucar",
    "marca": "Labial",
    "tipo": "Azucar",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Azucar",
    "marca": "Quita",
    "tipo": "Azucar",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Carne",
    "marca": "Rubor",
    "tipo": "Carne",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Carne",
    "marca": "Labial",
    "tipo": "Carne",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Carne",
    "marca": "Quita",
    "tipo": "Carne",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Condimentos",
    "marca": "Rubor",
    "tipo": "Condimentos",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Condimentos",
    "marca": "Labial",
    "tipo": "Condimentos",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Condimentos",
    "marca": "Quita",
    "tipo": "Condimentos",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Fideos",
    "marca": "Rubor",
    "tipo": "Fideos",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Fideos",
    "marca": "Labial",
    "tipo": "Fideos",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Fideos",
    "marca": "Quita",
    "tipo": "Fideos",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Frutas",
    "marca": "Rubor",
    "tipo": "Frutas",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Frutas",
    "marca": "Labial",
    "tipo": "Frutas",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Frutas",
    "marca": "Quita",
    "tipo": "Frutas",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Harina",
    "marca": "Rubor",
    "tipo": "Harina",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Harina",
    "marca": "Labial",
    "tipo": "Harina",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Harina",
    "marca": "Quita",
    "tipo": "Harina",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Huevos",
    "marca": "Rubor",
    "tipo": "Huevos",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Huevos",
    "marca": "Labial",
    "tipo": "Huevos",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Huevos",
    "marca": "Quita",
    "tipo": "Huevos",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Leche",
    "marca": "Rubor",
    "tipo": "Leche",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Leche",
    "marca": "Labial",
    "tipo": "Leche",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Leche",
    "marca": "Quita",
    "tipo": "Leche",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Menestras",
    "marca": "Rubor",
    "tipo": "Menestras",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Menestras",
    "marca": "Labial",
    "tipo": "Menestras",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Menestras",
    "marca": "Quita",
    "tipo": "Menestras",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Pan",
    "marca": "Rubor",
    "tipo": "Pan",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Pan",
    "marca": "Labial",
    "tipo": "Pan",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Pan",
    "marca": "Quita",
    "tipo": "Pan",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Pescado",
    "marca": "Rubor",
    "tipo": "Pescado",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Pescado",
    "marca": "Labial",
    "tipo": "Pescado",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Pescado",
    "marca": "Quita",
    "tipo": "Pescado",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Pollo",
    "marca": "Rubor",
    "tipo": "Pollo",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Pollo",
    "marca": "Labial",
    "tipo": "Pollo",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Pollo",
    "marca": "Quita",
    "tipo": "Pollo",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Rubor Líquido Maybelline Sunkisser Sol Search 4.7ml",
    "categoria": "Verduras",
    "marca": "Rubor",
    "tipo": "Verduras",
    "clase": null,
    "precioOnline": 52.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 7,
    "um": "ml",
    "pxum": 7557.14
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Labial Líquido Super Stay Matte Ink Maybelline Tono Amazonian",
    "categoria": "Verduras",
    "marca": "Labial",
    "tipo": "Verduras",
    "clase": null,
    "precioOnline": 67.9,
    "precioRegular": 0,
    "descuento": null,
    "vt": 1,
    "um": "u",
    "pxum": 67.9
  },
  {
    "fecha": "6/3/2026",
    "super": "Wong",
    "item": "Quita Esmalte Cutex 100ml",
    "categoria": "Verduras",
    "marca": "Quita",
    "tipo": "Verduras",
    "clase": null,
    "precioOnline": 12.3,
    "precioRegular": 0,
    "descuento": null,
    "vt": 100,
    "um": "ml",
    "pxum": 123
  }
];
